# TITANIC SURVIVAL

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
#to change directory
os.chdir("C:/Users/DELL/Desktop/Datasets")

In [3]:
train_data = pd.read_csv("titanic.csv")
train_g=pd.read_csv("titanic.csv")

In [4]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
train_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
train_data.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [7]:
train_data.shape

(891, 12)

In [8]:
train_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
train_data.Cabin.isnull().sum()

687

In [11]:
data1 = train_data.copy()

In [12]:
data1.drop('Cabin', axis = 1, inplace = True)

In [13]:
data1.drop("Ticket", axis = 1, inplace = True)

In [14]:
data1.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch     Fare Embarked  
0      0   7.2500        S  
1      0  71.2833        C  
2      0   7.9250        S  
3      0  53.1000        S  
4      0   8.0500        S

In [15]:
data1.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [16]:
data1.Sex.replace('male', 0, inplace = True)
data1.Sex.replace('female',1, inplace = True)

In [17]:
data1.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

      Fare Embarked  
0   7.2500        S  
1  71.2833        C  
2   7.9250        S  
3  53.1000        S  
4   8.0500        S

In [18]:
data1.corr()

PassengerId  Survived    Pclass       Sex       Age     SibSp  \
PassengerId     1.000000 -0.005007 -0.035144 -0.042939  0.036847 -0.057527   
Survived       -0.005007  1.000000 -0.338481  0.543351 -0.077221 -0.035322   
Pclass         -0.035144 -0.338481  1.000000 -0.131900 -0.369226  0.083081   
Sex            -0.042939  0.543351 -0.131900  1.000000 -0.093254  0.114631   
Age             0.036847 -0.077221 -0.369226 -0.093254  1.000000 -0.308247   
SibSp          -0.057527 -0.035322  0.083081  0.114631 -0.308247  1.000000   
Parch          -0.001652  0.081629  0.018443  0.245489 -0.189119  0.414838   
Fare            0.012658  0.257307 -0.549500  0.182333  0.096067  0.159651   

                Parch      Fare  
PassengerId -0.001652  0.012658  
Survived     0.081629  0.257307  
Pclass       0.018443 -0.549500  
Sex          0.245489  0.182333  
Age         -0.189119  0.096067  
SibSp        0.414838  0.159651  
Parch        1.000000  0.216225  
Fare         0.216225  1.000000

In [19]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null int64
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int64(6), object(2)
memory usage: 69.7+ KB


In [20]:
data1.describe()

PassengerId    Survived      Pclass         Sex         Age  \
count   891.000000  891.000000  891.000000  891.000000  714.000000   
mean    446.000000    0.383838    2.308642    0.352413   29.699118   
std     257.353842    0.486592    0.836071    0.477990   14.526497   
min       1.000000    0.000000    1.000000    0.000000    0.420000   
25%     223.500000    0.000000    2.000000    0.000000   20.125000   
50%     446.000000    0.000000    3.000000    0.000000   28.000000   
75%     668.500000    1.000000    3.000000    1.000000   38.000000   
max     891.000000    1.000000    3.000000    1.000000   80.000000   

            SibSp       Parch        Fare  
count  891.000000  891.000000  891.000000  
mean     0.523008    0.381594   32.204208  
std      1.102743    0.806057   49.693429  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    7.910400  
50%      0.000000    0.000000   14.454200  
75%      1.000000    0.000000   31.000000  
max      8.000000    6.000000  512.329200

In [21]:
data1.Age.fillna(data1.Age.median(), inplace = True)

In [22]:
data1.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       2
dtype: int64

In [23]:
data1.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [24]:
data1.Embarked.fillna(data1['Embarked'].value_counts().index[0], inplace = True)

In [25]:
data1.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [26]:

data1.drop('PassengerId', axis = 1, inplace = True)

In [27]:

corr = data1.corr()
corr.style.background_gradient(cmap = 'coolwarm')

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [29]:
data1.drop('Name', axis = 1, inplace = True)

In [30]:
data1.Embarked.unique()

array(['S', 'C', 'Q'], dtype=object)

In [31]:
data1.Embarked.value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [32]:
dataa2 = pd.get_dummies(data1, drop_first = False)

In [33]:
dataa2.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0         0       3    0  22.0      1      0   7.2500           0           0   
1         1       1    1  38.0      1      0  71.2833           1           0   
2         1       3    1  26.0      0      0   7.9250           0           0   
3         1       1    1  35.0      1      0  53.1000           0           0   
4         0       3    0  35.0      0      0   8.0500           0           0   

   Embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1

In [34]:
dataa2.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [35]:
y = dataa2.Survived.values
data3 = dataa2.drop("Survived", axis = 1)

In [36]:
data3.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0       3    0  22.0      1      0   7.2500           0           0   
1       1    1  38.0      1      0  71.2833           1           0   
2       3    1  26.0      0      0   7.9250           0           0   
3       1    1  35.0      1      0  53.1000           0           0   
4       3    0  35.0      0      0   8.0500           0           0   

   Embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1

In [37]:
data3.isnull().sum()

Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [38]:
features = list(data3.columns)

In [39]:
x = data3[features].values

In [41]:
train_x, test_x, train_y, test_y = train_test_split(x,y,test_size = 0.3, random_state = 0)

In [42]:
logistic = LogisticRegression(solver='lbfgs', max_iter=900)

In [43]:
logistic.fit(train_x, train_y)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=900,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [44]:
logistic.coef_

array([[-1.03264776e+00,  2.59964196e+00, -3.92567872e-02,
        -3.71371256e-01, -8.41995472e-02,  1.38788562e-03,
         1.43093531e-01,  1.45775857e-01, -2.84576992e-01]])

In [45]:
logistic.intercept_

array([2.36692746])

In [46]:
prediction = logistic.predict(test_x)

In [47]:
accuracy = accuracy_score(test_y, prediction)

In [48]:
accuracy

0.7985074626865671

# logistic regression after omitting Fare column

In [650]:
data4 = data3.copy()

In [651]:
data4.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0       3    0  22.0      1      0   7.2500           0           0   
1       1    1  38.0      1      0  71.2833           1           0   
2       3    1  26.0      0      0   7.9250           0           0   
3       1    1  35.0      1      0  53.1000           0           0   
4       3    0  35.0      0      0   8.0500           0           0   

   Embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1

In [652]:
data4.drop("Fare", axis = 1, inplace = True)


In [653]:
data4.head()

Pclass  Sex   Age  SibSp  Parch  Embarked_C  Embarked_Q  Embarked_S
0       3    0  22.0      1      0           0           0           1
1       1    1  38.0      1      0           1           0           0
2       3    1  26.0      0      0           0           0           1
3       1    1  35.0      1      0           0           0           1
4       3    0  35.0      0      0           0           0           1

In [654]:
y1 = dataa2.Survived

In [655]:
x1 = data4

In [656]:
train_x, test_x, train_y, test_y = train_test_split(x1,y1,test_size = 0.3, random_state = 0)

In [657]:
model = LogisticRegression(solver='lbfgs', max_iter=900)

In [658]:
model.fit(train_x, train_y)
model.coef_

array([[-1.07611348,  2.59941388, -0.03947438, -0.36418593, -0.06877363,
         0.16093847,  0.14282402, -0.29930368]])

In [659]:
model.intercept_

array([2.51323526])

In [660]:
prediction = model.predict(test_x)

In [661]:
accuracy = accuracy_score(test_y, prediction)
accuracy

0.8022388059701493

# TEST_DATA

In [362]:
test_data = pd.read_csv("test.csv")

In [363]:
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [364]:
test_data.shape

(418, 11)

In [365]:
test_data.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [366]:
test_data.drop("Cabin", axis=1, inplace = True)
test_data.drop("Fare",axis = 1, inplace = True)

In [367]:
test_data['Age'].fillna(test_data['Age'].value_counts().index[0], inplace = True)

In [368]:
test_data.shape


(418, 9)

In [369]:
test_data.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Embarked       0
dtype: int64

In [370]:

test_data.drop('Ticket', axis = 1, inplace = True)
test_data.drop('Name', axis = 1, inplace = True)

In [371]:
test_data.Sex.replace('male',0, inplace = True)
test_data.Sex.replace('female',1,inplace = True)

In [372]:
p_id = test_data.PassengerId

In [373]:
test_data.drop('PassengerId', axis = 1, inplace = True)

In [374]:
test_data.head()

Pclass  Sex   Age  SibSp  Parch Embarked
0       3    0  34.5      0      0        Q
1       3    1  47.0      1      0        S
2       2    0  62.0      0      0        Q
3       3    0  27.0      0      0        S
4       3    1  22.0      1      1        S

In [375]:
test = pd.get_dummies(test_data)

In [376]:
test_data.describe()

Pclass         Sex         Age       SibSp       Parch
count  418.000000  418.000000  418.000000  418.000000  418.000000
mean     2.265550    0.363636   28.982057    0.447368    0.392344
std      0.841838    0.481622   12.887063    0.896760    0.981429
min      1.000000    0.000000    0.170000    0.000000    0.000000
25%      1.000000    0.000000   23.000000    0.000000    0.000000
50%      3.000000    0.000000   24.000000    0.000000    0.000000
75%      3.000000    1.000000   35.750000    1.000000    0.000000
max      3.000000    1.000000   76.000000    8.000000    9.000000

In [377]:
test.head()

Pclass  Sex   Age  SibSp  Parch  Embarked_C  Embarked_Q  Embarked_S
0       3    0  34.5      0      0           0           1           0
1       3    1  47.0      1      0           0           0           1
2       2    0  62.0      0      0           0           1           0
3       3    0  27.0      0      0           0           0           1
4       3    1  22.0      1      1           0           0           1

In [379]:
pred = model.predict(test)

In [381]:
Submission = pd.DataFrame({'PassengerId':p_id,'Survived':pred})

In [384]:
Submission.to_csv('Submission.csv', index=False)